### ISSUE TITLE
Unable to run the simulation

### ISSUE THREAD

**Issue by sxlissxn** [shadow/tornettools#108]
Hello, im'm getting the following errors: ** Starting Shadow 3.2.0
00:00:00.000579 [391429:shadow] n/a [ERROR] [n/a] [shadow.rs:480] [shadow_rs::shadow::export] Failed to initialize the simulation
00:00:00.000631 [391429:shadow] n/a [ERROR] [n/a] [shadow.rs:480] [shadow_rs::shadow::export]
00:00:00.000668 [391429:shadow] n/a [ERROR] [n/a] [shadow.rs:480] [shadow_rs::shadow::export] Caused by:
00:00:00.000695 [391429:shadow] n/a [ERROR] [n/a] [shadow.rs:480] [shadow_rs::shadow::export]     0: Failed to configure host '4uthority1'
00:00:00.000721 [391429:shadow] n/a [ERROR] [n/a] [shadow.rs:480] [shadow_rs::shadow::export]     1: Failed to configure process '~/.local/bin/tor'

**Comment by sporksmith** [comment]
It looks like there was a problem trying to start `~/.local/bin/tor`. Is there a tor executable at that path?

If you need more help, it'd help us to have the exact command you're running, and shadow's full output. (In the output above it looks like shadow's stdout is being redirected to a file, and what you pasted is stderr, which only has ERROR-level log messages)

**Comment by sxlissxn** [comment]
Hello, thanks a lot for the help, i have added a symbolic link  at ~/.local/bin/tor and it is working, however, the simulation stays stagnant at 8% and it has been one hour, is it normal?

**Comment by robgjansen** [comment]
At that point in the simulation, Shadow is starting up many of the processes used for the simulation, so it can take a while depending on the resources available on your machine. You can check your CPU usage stats (with `top`, `htop` or similar) to see if Shadow has stalled or if it is still processing.

**Comment by sporksmith** [comment]
> If you need more help, it'd help us to have the exact command you're running, and shadow's full output. (In the output above it looks like shadow's stdout is being redirected to a file, and what you pasted is stderr, which only has ERROR-level log messages)

Oops, sorry I'd missed that this was an issue in the tornettools repo, not the shadow repo. When you run shadow via tornettools, the full shadow log should be in `shadow.log` in the output data directory.

> At that point in the simulation, Shadow is starting up many of the processes used for the simulation, so it can take a while depending on the resources available on your machine. You can check your CPU usage stats (with top, htop or similar) to see if Shadow has stalled or if it is still processing.

+1. If it is truly stuck, it may be a [busy loop](https://shadow.github.io/docs/guide/limitations.html?highlight=busy#busy-loops) problem. In such cases you'll typically see the process(es) with the busy loop using a lot of CPU.

**Comment by sxlissxn** [comment]
> +1. If it is truly stuck, it may be a [busy loop](https://shadow.github.io/docs/guide/limitations.html?highlight=busy#busy-loops) problem. In such cases you'll typically see the process(es) with the busy loop using a lot of CPU.

Hello, the busy loop is indeed the problem, it's working now, thanks a lot
