### ISSUE TITLE
Unable to run  "tornettools simulate tornet-0.01"

### ISSUE THREAD

**Issue by hellokob** [shadow/tornettools#112]
When I executed the command "tornettools simulate tornet-0.01", I got the following error:  Starting Shadow3.2.0

Error: process 'markovclient44exit.tgen.1004' exited with status Signaled(Signal(6)); expected end state was running but was signaled: SIGABRT
Error: process 'perfclient90exit.tgen.1004' exited with status Signaled(Signal(6)); expected end state was running but was signaled: SIGABRT
Error: Failed to run the simulation
Error: 
Error: Caused by:
Error:     210 managed processes in unexpected final state
** Shadow did not complete successfully: Failed to run the simulation
**   210 managed processes in unexpected final state
** See the log for details
2024-12-27 21:57:03 1735307823.297558 [tornettools] [INFO] Cleaning up
2024-12-27 21:57:03 1735307823.995994 [tornettools] [INFO] Done simulating; shadow returned code '1'
2024-12-27 21:57:03 1735307823.996515 [tornettools] [ERROR] Shadow simulation did not complete successfully.

shadow.log:
00:01:21.566512 [10371:shadow-worker] 00:05:00.000000000 [ERROR] [perfclient54exit:11.0.0.150] [process.rs:1564] [shadow_rs::host::process] process 'perfclient54exit.tgen.1004' exited with status Signaled(Signal(6)); expected end state was running but was signaled: SIGABRT
00:01:21.567353 [10334:shadow-worker] 00:05:00.000000000 [ERROR] [perfclient79exit:11.0.0.177] [process.rs:1564] [shadow_rs::host::process] process 'perfclient79exit.tgen.1004' exited with status Signaled(Signal(6)); expected end state was running but was signaled: SIGABRT
*****
00:15:59.053410 [10223:shadow] n/a [INFO] [n/a] [controller.rs:67] [shadow_rs::core::controller] Finished simulation
00:15:59.166581 [10223:shadow] n/a [ERROR] [n/a] [shadow.rs:480] [shadow_rs::shadow::export] Failed to run the simulation
00:15:59.166704 [10223:shadow] n/a [ERROR] [n/a] [shadow.rs:480] [shadow_rs::shadow::export] 
00:15:59.166773 [10223:shadow] n/a [ERROR] [n/a] [shadow.rs:480] [shadow_rs::shadow::export] Caused by:
00:15:59.166844 [10223:shadow] n/a [ERROR] [n/a] [shadow.rs:480] [shadow_rs::shadow::export]     210 managed processes in unexpected final state

**Comment by sporksmith** [comment]
You'll need to look at the stdout and stderr outputs of some of the individual processes to (hopefully) see why they're aborting. e.g. `shadow.data/hosts/perfclient54exit/tgen.1004.stdout` and  `shadow.data/hosts/perfclient54exit/tgen.1004.stderr`

**Comment by hellokob** [comment]
Thank you very much! In the Tor.1000.stdout file, I read that Tor has problems.

**Comment by hellokob** [comment]
> 您需要查看一些单个进程的 stdout 和 stderr 输出，以（希望）了解它们中止的原因。例如 和`shadow.data/hosts/perfclient54exit/tgen.1004.stdout``shadow.data/hosts/perfclient54exit/tgen.1004.stderr`

Thank you very much!
In the Tor.1000.stdout file, I read that Tor has problems.
