### ISSUE TITLE
Staging a simulation with a shorter time period than a month

### ISSUE THREAD

**Issue by hiromipaw** [shadow/tornettools#49]
We have been trying to run a simulation with shadow with a shorter time-period than a month. At the staging step in tornettools we pass folders were we have data from the days that we are interested in (as discussed in https://gitlab.torproject.org/tpo/network-health/metrics/analysis/-/issues/40008#note_2764299).

```
DATA_MONTH=2021-09
DATA_DAY=26
DATA_DELETE='09/25/2021 23:59:59'
DATA_END=$((DATA_DAY-1))
wget -O - https://collector.torproject.org/archive/relay-descriptors/consensuses/consensuses-$DATA_MONTH.tar.xz | tar xJ
wget -O - https://collector.torproject.org/archive/relay-descriptors/server-descriptors/server-descriptors-$DATA_MONTH.tar.xz | tar xJ
wget https://metrics.torproject.org/userstats-relay-country.csv
wget -O - https://collector.torproject.org/archive/onionperf/onionperf-$DATA_MONTH.tar.xz | tar xJ
wget -O bandwidth-$DATA_MONTH.csv "https://metrics.torproject.org/bandwidth.csv?start=$DATA_MONTH-$DATA_DAY&end=$DATA_MONTH-30"
pushd consensuses-$DATA_MONTH;
for DAY in `seq -w 01 $DATA_END`; do
     rm -fr $DAY;
done;
popd
pushd server-descriptors-$DATA_MONTH;
find . -type f ! -newermt "$DATA_DELETE" -delete;
popd
pushd onionperf-$DATA_MONTH
for DAY in `seq -w 01 $DATA_END`; do
     rm -fr $DAY;
done
popd
tornettools stage consensuses-$DATA_MONTH server-descriptors-$DATA_MONTH userstats-relay-country.csv ~/projects/tmodel-ccs2018.github.io/ --onionperf_data_path onionperf-$DATA_MONTH --bandwidth_data_path bandwidth-$DATA_MONTH.csv --geoip_path /usr/share/tor/geoip
```
When we run the simulation the shadow.log artifact has the error: "Bandwidth for host relay667middle must be non-zero" while networkinfo_staging.gml from the staging step doesn't have 0 for any nodes.

[shadow.log](https://github.com/shadow/tornettools/files/7688558/shadow.log)

[networkinfo_staging.gml.txt](https://github.com/shadow/tornettools/files/7688568/networkinfo_staging.gml.txt)

**Comment by sporksmith** [comment]
@hiromipaw were you able to check mikeperry's hypothesis?

> oh hrm yeah maybe it had measured=0 in its microdesc because sbws didn't get to it.. but this meems like something that should also randomly happen even with month-long datasets, if relays join at the end of a month

**Comment by sporksmith** [comment]
Ok, taking a look

**Comment by sporksmith** [comment]
Edited the snippet in OP slightly, and can now reproduce locally.

**Comment by sporksmith** [comment]
In the generated `relayinfo_staging_2021-09-26--2021-09-30.json` we have several entries with capacity 0, such as:

```
    "006FAD8F7FBF9A6605D6A2140472670309BC9934": {
      "address": "141.226.36.154",
      "bandwidth_burst": 1073741824,
      "bandwidth_capacity": 0,
      "bandwidth_rate": 1073741824,
      "country_code": "IL",
      "exit_frequency": 0.0,
      "fingerprint": "006FAD8F7FBF9A6605D6A2140472670309BC9934",
      "guard_frequency": 0.0,
      "running_frequency": 0.025,
      "weight": 0.0
    },
```

grepping for that IP address in the downloaded data, this one only has one server descriptor:

```
$ grep -R 141.226.36.154 .
./consensuses-2021-09/27/2021-09-27-01-00-00-consensus:r myNiceRelay AG+tj3+/mmYF1qIUBHJnAwm8mTQ IyUeTvp9GrJBRbnRCfzd2FfKO6k 2021-09-26 18:11:13 141.226.36.154 9001 0
./consensuses-2021-09/26/2021-09-26-20-00-00-consensus:r myNiceRelay AG+tj3+/mmYF1qIUBHJnAwm8mTQ IyUeTvp9GrJBRbnRCfzd2FfKO6k 2021-09-26 18:11:13 141.226.36.154 9001 0
./consensuses-2021-09/26/2021-09-26-21-00-00-consensus:r myNiceRelay AG+tj3+/mmYF1qIUBHJnAwm8mTQ IyUeTvp9GrJBRbnRCfzd2FfKO6k 2021-09-26 18:11:13 141.226.36.154 9001 0
./server-descriptors-2021-09/2/3/23251e4efa7d1ab24145b9d109fcddd857ca3ba9:router myNiceRelay 141.226.36.154 9001 0 0
./relayinfo_staging_2021-09-26--2021-09-30.json:      "address": "141.226.36.154",
```

Looking at that server descriptor, it looks like it indeed reported bandwidth 0:

```
bandwidth 1073741824 1073741824 0
```

tornettools looks at the bandwidth entries for each descriptor for a given relay and takes the max.

It's pretty clear we should filter out relays where the max ends up being 0.

I wonder if we should also drop individual descriptors with bandwidth 0?

**Comment by sporksmith** [comment]
It looks like tornettools already filters out relays with weight 0 (as in the examples above) in the generate step, but we end up with some relays that have 0 bandwidth and non-zero weight, such as:

```
    "0243E20F7FBAEFE823ECA53EAC7A7FC234EC98C7": {
      "address": "51.68.181.135",
      "bandwidth_burst": 1073741824,
      "bandwidth_capacity": 0,
      "bandwidth_rate": 1073741824,
      "country_code": "DE",
      "exit_frequency": 1.0,
      "fingerprint": "0243E20F7FBAEFE823ECA53EAC7A7FC234EC98C7",
      "guard_frequency": 0.0,
      "running_frequency": 0.14166666666666666,
      "weight": 7.634673600029329e-09
    },
```
