### ISSUE TITLE
mismatch when parsing shadow heartbeat message

### ISSUE THREAD

**Issue by shrlck221** [shadow/tornettools#6]
After running the simulation without errors for some reason "tornettools parse" is unable to parse the shadow.log file:

![shadowlogfailed](https://user-images.githubusercontent.com/81997761/113627853-61677c00-9664-11eb-9a11-b363dff7fb9e.png)

I can't find out what the problem is.

**Comment by robgjansen** [comment]
What version of Shadow did you use to run the experiment? In other words, what is the output of `shadow --version`?

In a recent version of the main branch of Shadow (about 1 week ago) we renamed the `slave` module to `manager`. If you are using the newer version of shadow, then the tornettools parser is still looking for the old name and there will be a mismatch.

I have a fix that I will merge soon; for now, you can grab the version from [the classic branch in my personal repo](https://github.com/robgjansen/tornettools/tree/classic).

**Comment by pmicos** [comment]
I'm using:

`Shadow v1.13.2-692-g12117c17 2021-03-30--09:30:08 running GLib v2.56.4 and IGraph v0.7.1`

I'll try with the version from your repo.

**Comment by shrlck221** [comment]
I'm using:

`Shadow v1.13.2-692-g12117c17 2021-03-30--09:30:08 running GLib v2.56.4 and IGraph v0.7.1`

I'll try with the version from your repo.

**Comment by robgjansen** [comment]
Indeed, the mismatch issue would affect that version and my branch should fix it.

**Comment by shrlck221** [comment]
I've staged/generated/simulated again with your version and the problem seems to be persisting.

![errorparsing](https://user-images.githubusercontent.com/81997761/113689060-3283f100-96ca-11eb-93d6-7f703979586d.png)

**Comment by shrlck221** [comment]
I've staged/generated/simulated again with your version and the problem seems to be persisting.

![errorparsing](https://user-images.githubusercontent.com/81997761/113697072-06b93900-96d3-11eb-9772-c950131af41f.png)

**Comment by robgjansen** [comment]
I assume you remembered to do a `pip install -I .` to install the new changes after checking out my branch. If so, then I'll have to investigate further. In the meantime, I think you _might_ be able to work around the issue by changing this line:

https://github.com/shadow/tornettools/blob/9d0d3b4ada4d14b37119ab71393a096b6481d47b/tornettools/parse_rusage.py#L14

like this:

```diff
-         return __parse_shadow_rusage(args)
+         return True
```

This only affects the `parse` step, so no need to run the `stage`, `generate`, or `simulate` steps again.

If you do give this a try, let me know how it goes.

**Comment by shrlck221** [comment]
I did a `pip install -I .` after checking out your branch.

I've tried by changing the line and then `pip install -I .` but the warning keeps appearing :(

**Comment by shrlck221** [comment]
Don't worry about it. I might have been doing something wrong and I haven't noticed. I'll wait for the fix. Thanks for your help!

**Comment by robgjansen** [comment]
Re-open if you are still experiencing issues with the latest main branch.
