### ISSUE TITLE
Need to explicitly disable ipv6 on tor @ 0.4.5.7

### ISSUE THREAD

**Issue by sporksmith** [shadow/tornettools#9]
Jaym  (@frochet:matrix.org) is working with tor-0.4.5.7 and found that it's trying to use ipv6 with the generated configs.

It looks like the phantom CI has "ORPort 9111 IPv4Only" in its tor configs. Maybe we need to add it here too?

**Comment by stevenengler** [comment]
I think the `IPv4Only` flag was added in 0fd1a854, are they using tornettools from the main branch?

**Comment by sporksmith** [comment]
They actually ran into it using the script in shadow-plugin-tor (shadow/shadow-plugin-tor#120), but said they'd just checked tornettools and saw it didn't generate it either. Maybe they were looking at an older version.

**Comment by sporksmith** [comment]
Thanks!
